language: go

env:
  - GO111MODULE=on
  global:
    - TRAVIS_GO_VERSION="$(cat .go-version)"

go:
  - 1.14.4
  - tip

before_install:
  - go get -t -v ./...

script:
  - go test ./internal/app/rpi-detector-mongo -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash) -t b9afdeee-b8eb-4a3b-afea-d0b38375b635