language: go

env:
  - GO111MODULE=on
  - ENVIRONMENT=test

go:
  - 1.14.4
  - tip

before_install:
  - go get -t -v ./cmd/rpihome ./config ./container/... ./dataservice/... ./model/... ./tool/... ./usecase/...

services: mongodb

before_script:
  - mongo rpi --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script:
  - go test -p 1 -race -coverprofile=coverage.txt -covermode=atomic ./config ./container/servicecontainer ./dataservice/... ./model/... ./tool/...

after_success:
  - bash <(curl -s https://codecov.io/bash) -t b9afdeee-b8eb-4a3b-afea-d0b38375b635