language: go

env:
  - GO111MODULE=on

go:
  - 1.14.4
  - tip

before_install:
  - go get -t -v ./...

services: mongodb

before_script:
  - mongo rpi --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script:
  - go test ./internal/app/rpi-detector-mongo ./internal/app/store -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash) -t b9afdeee-b8eb-4a3b-afea-d0b38375b635