version: "3.7"

services:
  rpihome:
    container_name: "rpihome"
    hostname: "rpihome"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    links:
      - mongodb_rpi
    restart: always
    depends_on:
      - mongodb_rpi
    volumes:
      - ./config/docker.json:/app/config/docker.json
      - /var/lib/motioneye:/var/lib/motioneye
      - ./backup:/app/backup

  mongodb_rpi:
    container_name: "rpihome_mongodb"
    image: mongo:4.0
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - ./docker/volume/mongodb:/data/db
      - ./docker/mongodb/.ash_history:/root/.ash_history:ro

  sqlite3_rpi:
    container_name: "rpihome_sqlite3"
    image: nouchka/sqlite3:latest
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/

  motioneye:
    container_name: "rpihome_motioneye"
    image: "ccrisan/motioneye:master-armhf"
    ports: 
      - "8765:8765"
    hostname: "motioneye"
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/motioneye:/etc/motioneye
      - /var/lib/motioneye:/var/lib/motioneye
      - ./scripts:/etc/scripts
    devices: 
      - /dev/video0

networks:
  default:
    external:
      name: rpi-home_default