version: "3.7"

services:
  rpihome:
    container_name: "rpihome"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    links:
      - mongodb
    restart: always
    depends_on:
      - mongodb
      - motioneye
    volumes:
      - ./config/docker.json:/app/config/docker.json
      - ./detector:/app/build/out

  mongodb:
    container_name: "rpihome_mongodb"
    image: nonoroazoro/rpi-mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - ./docker/volume/mongodb:/data/db
      - ./docker/mongodb/.ash_history:/root/.ash_history:ro
    
  motioneye:
    container_name: "rpihome_motioneye"
    image: "ccrisan/motioneye:master-armhf"
    ports: 
      - "8765:8765"
    hostname: "motioneye"
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/motioneye:/etc/motioneye
      - /var/lib/motioneye:/var/lib/motioneye
      - ./scripts:/etc/scripts
    devices: 
      - /dev/video0
